import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_blog_posts_url_pattern" AS ENUM('blog', 'legacy-root');
  CREATE TYPE "public"."enum__blog_posts_v_version_url_pattern" AS ENUM('blog', 'legacy-root');
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '85vh'::text;
  DROP TYPE "public"."enum_pages_blocks_hero_hero_height";
  CREATE TYPE "public"."enum_pages_blocks_hero_hero_height" AS ENUM('85vh', '100vh', '70vh');
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '85vh'::"public"."enum_pages_blocks_hero_hero_height";
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE "public"."enum_pages_blocks_hero_hero_height" USING "hero_height"::"public"."enum_pages_blocks_hero_hero_height";
  ALTER TABLE "pages_blocks_rich_content" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_rich_content" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_rich_content_background";
  CREATE TYPE "public"."enum_pages_blocks_rich_content_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_rich_content" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_rich_content_background";
  ALTER TABLE "pages_blocks_rich_content" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_rich_content_background" USING "background"::"public"."enum_pages_blocks_rich_content_background";
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "background" SET DEFAULT 'gradient'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_background";
  CREATE TYPE "public"."enum_pages_blocks_cta_background" AS ENUM('gradient', 'grass', 'grass-alt');
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "background" SET DEFAULT 'gradient'::"public"."enum_pages_blocks_cta_background";
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_cta_background" USING "background"::"public"."enum_pages_blocks_cta_background";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_faq_background";
  CREATE TYPE "public"."enum_pages_blocks_faq_background" AS ENUM('grass', 'grass-alt', 'grass-to-blue');
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_faq_background";
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_faq_background" USING "background"::"public"."enum_pages_blocks_faq_background";
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum_pages_blocks_feature_grid_background";
  CREATE TYPE "public"."enum_pages_blocks_feature_grid_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum_pages_blocks_feature_grid_background";
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_feature_grid_background" USING "background"::"public"."enum_pages_blocks_feature_grid_background";
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum_pages_blocks_image_text_background";
  CREATE TYPE "public"."enum_pages_blocks_image_text_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum_pages_blocks_image_text_background";
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_image_text_background" USING "background"::"public"."enum_pages_blocks_image_text_background";
  ALTER TABLE "pages_blocks_trust_bar" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_trust_bar" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_trust_bar_background";
  CREATE TYPE "public"."enum_pages_blocks_trust_bar_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_trust_bar" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_trust_bar_background";
  ALTER TABLE "pages_blocks_trust_bar" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_trust_bar_background" USING "background"::"public"."enum_pages_blocks_trust_bar_background";
  ALTER TABLE "pages_blocks_testimonial" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_testimonial" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_testimonial_background";
  CREATE TYPE "public"."enum_pages_blocks_testimonial_background" AS ENUM('grass', 'grass-alt', 'grass-to-blue');
  ALTER TABLE "pages_blocks_testimonial" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_testimonial_background";
  ALTER TABLE "pages_blocks_testimonial" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_testimonial_background" USING "background"::"public"."enum_pages_blocks_testimonial_background";
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_stats_background";
  CREATE TYPE "public"."enum_pages_blocks_stats_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_stats_background";
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_stats_background" USING "background"::"public"."enum_pages_blocks_stats_background";
  ALTER TABLE "pages_blocks_pain_points" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_pain_points" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_pain_points_background";
  CREATE TYPE "public"."enum_pages_blocks_pain_points_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_pain_points" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_pain_points_background";
  ALTER TABLE "pages_blocks_pain_points" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_pain_points_background" USING "background"::"public"."enum_pages_blocks_pain_points_background";
  ALTER TABLE "pages_blocks_steps_process" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_steps_process" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum_pages_blocks_steps_process_background";
  CREATE TYPE "public"."enum_pages_blocks_steps_process_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_steps_process" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum_pages_blocks_steps_process_background";
  ALTER TABLE "pages_blocks_steps_process" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_steps_process_background" USING "background"::"public"."enum_pages_blocks_steps_process_background";
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum_pages_blocks_service_area_background";
  CREATE TYPE "public"."enum_pages_blocks_service_area_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum_pages_blocks_service_area_background";
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_service_area_background" USING "background"::"public"."enum_pages_blocks_service_area_background";
  ALTER TABLE "pages_blocks_team_cards" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_team_cards" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum_pages_blocks_team_cards_background";
  CREATE TYPE "public"."enum_pages_blocks_team_cards_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "pages_blocks_team_cards" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum_pages_blocks_team_cards_background";
  ALTER TABLE "pages_blocks_team_cards" ALTER COLUMN "background" SET DATA TYPE "public"."enum_pages_blocks_team_cards_background" USING "background"::"public"."enum_pages_blocks_team_cards_background";
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '85vh'::text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_hero_height";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_hero_height" AS ENUM('85vh', '100vh', '70vh');
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '85vh'::"public"."enum__pages_v_blocks_hero_hero_height";
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE "public"."enum__pages_v_blocks_hero_hero_height" USING "hero_height"::"public"."enum__pages_v_blocks_hero_hero_height";
  ALTER TABLE "_pages_v_blocks_rich_content" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_rich_content" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_rich_content_background";
  CREATE TYPE "public"."enum__pages_v_blocks_rich_content_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_rich_content" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_rich_content_background";
  ALTER TABLE "_pages_v_blocks_rich_content" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_rich_content_background" USING "background"::"public"."enum__pages_v_blocks_rich_content_background";
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "background" SET DEFAULT 'gradient'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_background";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_background" AS ENUM('gradient', 'grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "background" SET DEFAULT 'gradient'::"public"."enum__pages_v_blocks_cta_background";
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_cta_background" USING "background"::"public"."enum__pages_v_blocks_cta_background";
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_faq_background";
  CREATE TYPE "public"."enum__pages_v_blocks_faq_background" AS ENUM('grass', 'grass-alt', 'grass-to-blue');
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_faq_background";
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_faq_background" USING "background"::"public"."enum__pages_v_blocks_faq_background";
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum__pages_v_blocks_feature_grid_background";
  CREATE TYPE "public"."enum__pages_v_blocks_feature_grid_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum__pages_v_blocks_feature_grid_background";
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_feature_grid_background" USING "background"::"public"."enum__pages_v_blocks_feature_grid_background";
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum__pages_v_blocks_image_text_background";
  CREATE TYPE "public"."enum__pages_v_blocks_image_text_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum__pages_v_blocks_image_text_background";
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_image_text_background" USING "background"::"public"."enum__pages_v_blocks_image_text_background";
  ALTER TABLE "_pages_v_blocks_trust_bar" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_trust_bar" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_trust_bar_background";
  CREATE TYPE "public"."enum__pages_v_blocks_trust_bar_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_trust_bar" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_trust_bar_background";
  ALTER TABLE "_pages_v_blocks_trust_bar" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_trust_bar_background" USING "background"::"public"."enum__pages_v_blocks_trust_bar_background";
  ALTER TABLE "_pages_v_blocks_testimonial" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_testimonial" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_testimonial_background";
  CREATE TYPE "public"."enum__pages_v_blocks_testimonial_background" AS ENUM('grass', 'grass-alt', 'grass-to-blue');
  ALTER TABLE "_pages_v_blocks_testimonial" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_testimonial_background";
  ALTER TABLE "_pages_v_blocks_testimonial" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_testimonial_background" USING "background"::"public"."enum__pages_v_blocks_testimonial_background";
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_stats_background";
  CREATE TYPE "public"."enum__pages_v_blocks_stats_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_stats_background";
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_stats_background" USING "background"::"public"."enum__pages_v_blocks_stats_background";
  ALTER TABLE "_pages_v_blocks_pain_points" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_pain_points" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_pain_points_background";
  CREATE TYPE "public"."enum__pages_v_blocks_pain_points_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_pain_points" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_pain_points_background";
  ALTER TABLE "_pages_v_blocks_pain_points" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_pain_points_background" USING "background"::"public"."enum__pages_v_blocks_pain_points_background";
  ALTER TABLE "_pages_v_blocks_steps_process" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_steps_process" ALTER COLUMN "background" SET DEFAULT 'grass'::text;
  DROP TYPE "public"."enum__pages_v_blocks_steps_process_background";
  CREATE TYPE "public"."enum__pages_v_blocks_steps_process_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_steps_process" ALTER COLUMN "background" SET DEFAULT 'grass'::"public"."enum__pages_v_blocks_steps_process_background";
  ALTER TABLE "_pages_v_blocks_steps_process" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_steps_process_background" USING "background"::"public"."enum__pages_v_blocks_steps_process_background";
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum__pages_v_blocks_service_area_background";
  CREATE TYPE "public"."enum__pages_v_blocks_service_area_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum__pages_v_blocks_service_area_background";
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_service_area_background" USING "background"::"public"."enum__pages_v_blocks_service_area_background";
  ALTER TABLE "_pages_v_blocks_team_cards" ALTER COLUMN "background" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_team_cards" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::text;
  DROP TYPE "public"."enum__pages_v_blocks_team_cards_background";
  CREATE TYPE "public"."enum__pages_v_blocks_team_cards_background" AS ENUM('grass', 'grass-alt');
  ALTER TABLE "_pages_v_blocks_team_cards" ALTER COLUMN "background" SET DEFAULT 'grass-alt'::"public"."enum__pages_v_blocks_team_cards_background";
  ALTER TABLE "_pages_v_blocks_team_cards" ALTER COLUMN "background" SET DATA TYPE "public"."enum__pages_v_blocks_team_cards_background" USING "background"::"public"."enum__pages_v_blocks_team_cards_background";
  ALTER TABLE "pages_blocks_rich_content" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_testimonial" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_pain_points" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_steps_process" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_rich_content" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_testimonial" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_pain_points" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_steps_process" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "show_divider" SET DEFAULT false;
  ALTER TABLE "pages_blocks_image_text" ADD COLUMN "fallback_image" varchar;
  ALTER TABLE "_pages_v_blocks_image_text" ADD COLUMN "fallback_image" varchar;
  ALTER TABLE "blog_posts" ADD COLUMN "url_pattern" "enum_blog_posts_url_pattern" DEFAULT 'blog';
  ALTER TABLE "_blog_posts_v" ADD COLUMN "version_url_pattern" "enum__blog_posts_v_version_url_pattern" DEFAULT 'blog';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_blocks_rich_content_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_rich_content_background" ADD VALUE 'cream';
  ALTER TYPE "public"."enum_pages_blocks_cta_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_faq_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_faq_background" ADD VALUE 'cream';
  ALTER TYPE "public"."enum_pages_blocks_feature_grid_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum_pages_blocks_feature_grid_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_image_text_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum_pages_blocks_image_text_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_trust_bar_background" ADD VALUE 'blue' BEFORE 'grass';
  ALTER TYPE "public"."enum_pages_blocks_testimonial_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_stats_background" ADD VALUE 'blue' BEFORE 'grass';
  ALTER TYPE "public"."enum_pages_blocks_stats_background" ADD VALUE 'cream';
  ALTER TYPE "public"."enum_pages_blocks_pain_points_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_steps_process_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum_pages_blocks_service_area_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum_pages_blocks_team_cards_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum__pages_v_blocks_rich_content_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_rich_content_background" ADD VALUE 'cream';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_faq_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_faq_background" ADD VALUE 'cream';
  ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum__pages_v_blocks_feature_grid_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_image_text_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum__pages_v_blocks_image_text_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_trust_bar_background" ADD VALUE 'blue' BEFORE 'grass';
  ALTER TYPE "public"."enum__pages_v_blocks_testimonial_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_stats_background" ADD VALUE 'blue' BEFORE 'grass';
  ALTER TYPE "public"."enum__pages_v_blocks_stats_background" ADD VALUE 'cream';
  ALTER TYPE "public"."enum__pages_v_blocks_pain_points_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_steps_process_background" ADD VALUE 'blue';
  ALTER TYPE "public"."enum__pages_v_blocks_service_area_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TYPE "public"."enum__pages_v_blocks_team_cards_background" ADD VALUE 'cream' BEFORE 'grass';
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '100vh'::text;
  DROP TYPE "public"."enum_pages_blocks_hero_hero_height";
  CREATE TYPE "public"."enum_pages_blocks_hero_hero_height" AS ENUM('100vh', '85vh', '70vh');
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '100vh'::"public"."enum_pages_blocks_hero_hero_height";
  ALTER TABLE "pages_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE "public"."enum_pages_blocks_hero_hero_height" USING "hero_height"::"public"."enum_pages_blocks_hero_hero_height";
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '100vh'::text;
  DROP TYPE "public"."enum__pages_v_blocks_hero_hero_height";
  CREATE TYPE "public"."enum__pages_v_blocks_hero_hero_height" AS ENUM('100vh', '85vh', '70vh');
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DEFAULT '100vh'::"public"."enum__pages_v_blocks_hero_hero_height";
  ALTER TABLE "_pages_v_blocks_hero" ALTER COLUMN "hero_height" SET DATA TYPE "public"."enum__pages_v_blocks_hero_hero_height" USING "hero_height"::"public"."enum__pages_v_blocks_hero_hero_height";
  ALTER TABLE "pages_blocks_rich_content" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "pages_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "pages_blocks_trust_bar" ALTER COLUMN "background" SET DEFAULT 'blue';
  ALTER TABLE "pages_blocks_testimonial" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'blue';
  ALTER TABLE "pages_blocks_pain_points" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_steps_process" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "pages_blocks_service_area" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "pages_blocks_team_cards" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "_pages_v_blocks_rich_content" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "_pages_v_blocks_image_text" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "_pages_v_blocks_trust_bar" ALTER COLUMN "background" SET DEFAULT 'blue';
  ALTER TABLE "_pages_v_blocks_testimonial" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_stats" ALTER COLUMN "background" SET DEFAULT 'blue';
  ALTER TABLE "_pages_v_blocks_pain_points" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_steps_process" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "show_divider" SET DEFAULT true;
  ALTER TABLE "_pages_v_blocks_service_area" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "_pages_v_blocks_team_cards" ALTER COLUMN "background" SET DEFAULT 'cream';
  ALTER TABLE "pages_blocks_image_text" DROP COLUMN "fallback_image";
  ALTER TABLE "_pages_v_blocks_image_text" DROP COLUMN "fallback_image";
  ALTER TABLE "blog_posts" DROP COLUMN "url_pattern";
  ALTER TABLE "_blog_posts_v" DROP COLUMN "version_url_pattern";
  DROP TYPE "public"."enum_blog_posts_url_pattern";
  DROP TYPE "public"."enum__blog_posts_v_version_url_pattern";`)
}
