/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'blog-posts': BlogPost;
    authors: Author;
    tags: Tag;
    testimonials: Testimonial;
    'city-pages': CityPage;
    services: Service;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'city-pages': CityPagesSelect<false> | CityPagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admins manage users and delete content. Editors can create and update content.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image content for accessibility and SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug. Use "/" for homepage.
   */
  slug: string;
  layout: (
    | {
        /**
         * Main headline. Uppercase Lexend Bold.
         */
        heading: string;
        /**
         * Supporting text. Zilla Slab Regular.
         */
        subheading?: string | null;
        /**
         * Full-width background. Preloaded as LCP element.
         */
        backgroundImage?: (number | null) | Media;
        /**
         * Static fallback image key (e.g. "hero-lawn") when no CMS backgroundImage is set. Maps to /images/{key}.webp.
         */
        fallbackImage?: string | null;
        /**
         * Hero section height.
         */
        heroHeight?: ('85vh' | '100vh' | '70vh') | null;
        cta?: {
          text?: string | null;
          url?: string | null;
          style?: ('primary' | 'secondary') | null;
        };
        /**
         * JSON array of trust items shown at hero bottom. E.g. ["5-Star Rated", "Nearly 5,000 Clients Served"]. Leave empty for no trust strip in hero.
         */
        trustStrip?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        layout?: ('left' | 'centered') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        heading?: string | null;
        /**
         * Show gold divider below heading.
         */
        showDivider?: boolean | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'richContent';
      }
    | {
        heading: string;
        body?: string | null;
        buttonText: string;
        buttonUrl: string;
        buttonStyle?: ('primary' | 'secondary') | null;
        /**
         * Friction reducer below button (e.g. "Free quote. No obligation.").
         */
        subtext?: string | null;
        /**
         * Show a contact form alongside the CTA button.
         */
        showForm?: boolean | null;
        background?: ('gradient' | 'grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        heading?: string | null;
        showDivider?: boolean | null;
        items: {
          question: string;
          answer: string;
          id?: string | null;
        }[];
        moreLink?: {
          text?: string | null;
          url?: string | null;
        };
        /**
         * Output FAQPage JSON-LD schema.
         */
        generateSchema?: boolean | null;
        background?: ('grass' | 'grass-alt' | 'grass-to-blue') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        heading: string;
        showDivider?: boolean | null;
        items: {
          title: string;
          description: string;
          /**
           * SVG icon (optional).
           */
          icon?: (number | null) | Media;
          /**
           * Optional link URL.
           */
          link?: string | null;
          /**
           * Link text (e.g. "Learn more").
           */
          linkText?: string | null;
          id?: string | null;
        }[];
        columns?: ('2' | '3' | '4') | null;
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureGrid';
      }
    | {
        heading?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        image?: (number | null) | Media;
        /**
         * Static image filename (without /images/ prefix) used when CMS media is not set
         */
        fallbackImage?: string | null;
        imageAlt: string;
        imagePosition?: ('right' | 'left') | null;
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imageText';
      }
    | {
        metrics: {
          /**
           * The stat (e.g. "9", "5,000+", "219+").
           */
          number: string;
          /**
           * Optional label. If empty, "number" field is used as the full flowing text item.
           */
          label?: string | null;
          id?: string | null;
        }[];
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustBar';
      }
    | {
        heading?: string | null;
        showDivider?: boolean | null;
        quotes: {
          text: string;
          name: string;
          /**
           * City/suburb (e.g. "Sammamish, WA").
           */
          city?: string | null;
          rating?: number | null;
          id?: string | null;
        }[];
        moreLink?: {
          text?: string | null;
          url?: string | null;
        };
        background?: ('grass' | 'grass-alt' | 'grass-to-blue') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonial';
      }
    | {
        heading?: string | null;
        items: {
          number: string;
          label: string;
          description?: string | null;
          id?: string | null;
        }[];
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        /**
         * AI-extractable definition block. 2-3 clear, independently citable sentences. Place in the first 30% of page content. Used for speakable schema.
         */
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'geoDefinition';
      }
    | {
        heading: string;
        showDivider?: boolean | null;
        /**
         * Empathy copy. In the ICP language.
         */
        body?: string | null;
        /**
         * Optional bullet points of specific pain points.
         */
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'painPoints';
      }
    | {
        heading: string;
        showDivider?: boolean | null;
        steps: {
          /**
           * Step number (e.g. "01").
           */
          number: string;
          title: string;
          /**
           * Full step description (used as detail in progressive disclosure, and for SEO/schema).
           */
          description: string;
          /**
           * Short 1-line summary shown by default. If empty, the full description is shown.
           */
          summary?: string | null;
          id?: string | null;
        }[];
        cta?: {
          text?: string | null;
          url?: string | null;
          subtext?: string | null;
        };
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stepsProcess';
      }
    | {
        heading?: string | null;
        showDivider?: boolean | null;
        cities: {
          name: string;
          /**
           * Link to city page (e.g. "/mole-control-sammamish/").
           */
          url: string;
          id?: string | null;
        }[];
        allAreasLink?: {
          text?: string | null;
          url?: string | null;
        };
        countyText?: string | null;
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceArea';
      }
    | {
        heading: string;
        subheading?: string | null;
        showDivider?: boolean | null;
        members: {
          name: string;
          role: string;
          bio: string;
          /**
           * Static image key (e.g. "team-spencer"). Maps to /images/{key}.webp in site/public/images/.
           */
          photoKey: string;
          id?: string | null;
        }[];
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'teamCards';
      }
    | {
        heading: string;
        services: {
          name: string;
          link?: string | null;
          bestFor: string;
          howItWorks: string;
          pricing: string;
          guarantee?: string | null;
          duration?: string | null;
          reporting?: string | null;
          id?: string | null;
        }[];
        footnote?: string | null;
        background?: ('grass' | 'grass-alt') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceComparison';
      }
    | {
        /**
         * Optional caption displayed below the table. Describe what the table shows.
         */
        caption?: string | null;
        /**
         * First row is a header row (renders as <th> elements).
         */
        hasHeader?: boolean | null;
        /**
         * Table rows. All rows must have the same number of cells (2-6).
         */
        rows: {
          cells: {
            /**
             * Cell text content.
             */
            content: string;
            id?: string | null;
          }[];
          id?: string | null;
        }[];
        background?: ('grass' | 'grass-alt' | 'cream') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'table';
      }
    | {
        /**
         * TL;DR summary. Target: 40-60 words. This text renders with id="blog-definition-block" for speakable schema and AI extraction.
         */
        content: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'tldr';
      }
  )[];
  meta?: {
    /**
     * Override the page <title>. Defaults to page title + site name.
     */
    title?: string | null;
    /**
     * Meta description. Max 160 characters.
     */
    description?: string | null;
    /**
     * Open Graph image for social sharing.
     */
    ogImage?: (number | null) | Media;
    /**
     * Prevent search engines from indexing this page.
     */
    noIndex?: boolean | null;
  };
  schema?: {
    /**
     * JSON-LD @type for this page.
     */
    type?: ('WebPage' | 'AboutPage' | 'ContactPage' | 'FAQPage' | 'CollectionPage' | 'Service') | null;
    /**
     * Additional JSON-LD to inject. Merged with auto-generated schema.
     */
    customJsonLd?: string | null;
  };
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  publishDate: string;
  author: number | Author;
  status: 'draft' | 'published';
  /**
   * Used in blog index cards and social sharing.
   */
  excerpt: string;
  /**
   * GEO-extractable paragraph. 2-3 clear, citable sentences for AI engines.
   */
  definitionBlock?: string | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * 3-5 questions in homeowner language. FAQPage schema generated.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    metaTitle?: string | null;
    metaDescription: string;
    primaryKeyword: string;
  };
  keywordCluster: 'mole-control' | 'biology' | 'diy-pro' | 'cost-value' | 'safety' | 'seasonal' | 'commercial';
  /**
   * "blog" → /blog/{slug}/. "legacy-root" → /{slug}/ (preserves pre-migration indexed URL).
   */
  urlPattern: 'blog' | 'legacy-root';
  tags?: (number | Tag)[] | null;
  featuredImage?: (number | null) | Media;
  wordCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  veteranStatus?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * Customer first name (from Google review).
   */
  name: string;
  /**
   * Customer city/suburb (e.g. "Sammamish, WA").
   */
  city?: string | null;
  /**
   * Review excerpt for cards. 1-3 sentences.
   */
  quote: string;
  /**
   * Full Google review text for the reviews page.
   */
  fullQuote?: string | null;
  rating?: number | null;
  /**
   * Which service this review relates to.
   */
  serviceType?: ('tmcp' | 'one-time' | 'commercial') | null;
  /**
   * Primary concern this review addresses.
   */
  concern?: ('effectiveness' | 'safety' | 'ongoing' | 'professionalism' | 'value') | null;
  /**
   * Link to the original Google review.
   */
  googleReviewUrl?: string | null;
  /**
   * Which GBP location this review is from.
   */
  gbpLocation?: ('location-1' | 'location-2' | 'location-3') | null;
  dateGiven?: string | null;
  /**
   * Show on homepage and priority placements.
   */
  featured?: boolean | null;
  status?: ('draft' | 'published') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-pages".
 */
export interface CityPage {
  id: number;
  /**
   * City name (e.g. "Sammamish").
   */
  cityName: string;
  /**
   * URL slug (e.g. "sammamish"). Used as /mole-control-{slug}/.
   */
  slug: string;
  county: 'king' | 'pierce' | 'thurston' | 'snohomish';
  priority?: ('priority' | 'standard') | null;
  /**
   * H1 for this city page (e.g. "Mole Control in Sammamish, WA").
   */
  headline: string;
  /**
   * City-specific intro. 2-3 sentences with local references.
   */
  introText: string;
  /**
   * Neighborhoods, local landmarks, soil conditions, common mole species.
   */
  localDetails?: string | null;
  /**
   * Additional city-specific content.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * City-specific FAQs (3-5 questions). FAQPage schema generated.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    primaryKeyword: string;
  };
  /**
   * City population (for local stats).
   */
  population?: number | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Service name (e.g. "Total Mole Control Program").
   */
  name: string;
  /**
   * Short name for cards (e.g. "TMCP").
   */
  shortName?: string | null;
  slug: string;
  serviceType: 'residential-recurring' | 'residential-onetime' | 'commercial';
  pricing?: {
    /**
     * Display price (e.g. "$100/month", "$450 flat rate", "Custom quote").
     */
    price?: string | null;
    /**
     * Setup fee if applicable (e.g. "$150").
     */
    setupFee?: string | null;
    /**
     * Minimum commitment (e.g. "12-month minimum").
     */
    commitment?: string | null;
    /**
     * Property size limit (e.g. "Under 1 acre").
     */
    propertyLimit?: string | null;
  };
  /**
   * Short description for service cards. 2-3 sentences.
   */
  summary: string;
  /**
   * Guarantee text specific to this service.
   */
  guarantee?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions and lead capture audit trail. Source of truth independent of GHL / Jobber.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  zipCode: string;
  service: 'tmcp' | 'one-time' | 'commercial' | 'other';
  message?: string | null;
  source: 'website-contact' | 'scoreapp' | 'phone' | 'other';
  status:
    | 'new'
    | 'synced-ghl'
    | 'synced-jobber'
    | 'synced-both'
    | 'duplicate'
    | 'outside-area'
    | 'spam'
    | 'failed-sync';
  /**
   * Set automatically from ZIP code against the WA service-area allowlist.
   */
  inServiceArea?: boolean | null;
  /**
   * IDs returned from external systems after a successful sync.
   */
  externalIds?: {
    ghlContactId?: string | null;
    jobberClientId?: string | null;
  };
  /**
   * Each attempted sync with outcome. Latest attempt last.
   */
  syncLog?:
    | {
        destination: 'ghl' | 'jobber';
        success: boolean;
        error?: string | null;
        timestamp: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Client IP for audit / spam investigation.
   */
  ipAddress?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'city-pages';
        value: number | CityPage;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              fallbackImage?: T;
              heroHeight?: T;
              cta?:
                | T
                | {
                    text?: T;
                    url?: T;
                    style?: T;
                  };
              trustStrip?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              content?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              body?: T;
              buttonText?: T;
              buttonUrl?: T;
              buttonStyle?: T;
              subtext?: T;
              showForm?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              moreLink?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              generateSchema?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    linkText?: T;
                    id?: T;
                  };
              columns?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        imageText?:
          | T
          | {
              heading?: T;
              content?: T;
              image?: T;
              fallbackImage?: T;
              imageAlt?: T;
              imagePosition?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        trustBar?:
          | T
          | {
              metrics?:
                | T
                | {
                    number?: T;
                    label?: T;
                    id?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        testimonial?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              quotes?:
                | T
                | {
                    text?: T;
                    name?: T;
                    city?: T;
                    rating?: T;
                    id?: T;
                  };
              moreLink?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    number?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        geoDefinition?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        painPoints?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              body?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        stepsProcess?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    summary?: T;
                    id?: T;
                  };
              cta?:
                | T
                | {
                    text?: T;
                    url?: T;
                    subtext?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        serviceArea?:
          | T
          | {
              heading?: T;
              showDivider?: T;
              cities?:
                | T
                | {
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              allAreasLink?:
                | T
                | {
                    text?: T;
                    url?: T;
                  };
              countyText?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        teamCards?:
          | T
          | {
              heading?: T;
              subheading?: T;
              showDivider?: T;
              members?:
                | T
                | {
                    name?: T;
                    role?: T;
                    bio?: T;
                    photoKey?: T;
                    id?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        serviceComparison?:
          | T
          | {
              heading?: T;
              services?:
                | T
                | {
                    name?: T;
                    link?: T;
                    bestFor?: T;
                    howItWorks?: T;
                    pricing?: T;
                    guarantee?: T;
                    duration?: T;
                    reporting?: T;
                    id?: T;
                  };
              footnote?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        table?:
          | T
          | {
              caption?: T;
              hasHeader?: T;
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          content?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              background?: T;
              id?: T;
              blockName?: T;
            };
        tldr?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        noIndex?: T;
      };
  schema?:
    | T
    | {
        type?: T;
        customJsonLd?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishDate?: T;
  author?: T;
  status?: T;
  excerpt?: T;
  definitionBlock?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        primaryKeyword?: T;
      };
  keywordCluster?: T;
  urlPattern?: T;
  tags?: T;
  featuredImage?: T;
  wordCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  veteranStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  city?: T;
  quote?: T;
  fullQuote?: T;
  rating?: T;
  serviceType?: T;
  concern?: T;
  googleReviewUrl?: T;
  gbpLocation?: T;
  dateGiven?: T;
  featured?: T;
  status?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-pages_select".
 */
export interface CityPagesSelect<T extends boolean = true> {
  cityName?: T;
  slug?: T;
  county?: T;
  priority?: T;
  headline?: T;
  introText?: T;
  localDetails?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        primaryKeyword?: T;
      };
  population?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  slug?: T;
  serviceType?: T;
  pricing?:
    | T
    | {
        price?: T;
        setupFee?: T;
        commitment?: T;
        propertyLimit?: T;
      };
  summary?: T;
  guarantee?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  zipCode?: T;
  service?: T;
  message?: T;
  source?: T;
  status?: T;
  inServiceArea?: T;
  externalIds?:
    | T
    | {
        ghlContactId?: T;
        jobberClientId?: T;
      };
  syncLog?:
    | T
    | {
        destination?: T;
        success?: T;
        error?: T;
        timestamp?: T;
        id?: T;
      };
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  phone?: string | null;
  logo?: (number | null) | Media;
  siteUrl: string;
  defaultOgImage?: (number | null) | Media;
  social?: {
    googleBusiness?: string | null;
    facebook?: string | null;
    nextdoor?: string | null;
    yelp?: string | null;
  };
  /**
   * Tracking IDs. Leave blank to disable.
   */
  analytics?: {
    /**
     * Google Analytics 4 Measurement ID (G-XXXXXXX).
     */
    ga4Id?: string | null;
    /**
     * Meta/Facebook Pixel ID.
     */
    metaPixelId?: string | null;
    /**
     * Google Ads conversion tracking ID.
     */
    adwordsId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems: {
    label: string;
    url: string;
    /**
     * Dropdown items. Leave empty for a simple link.
     */
    children?:
      | {
          label: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  ctaButton: {
    text: string;
    url: string;
  };
  /**
   * Phone number displayed in header (desktop).
   */
  phone?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  brandDescription?: string | null;
  columns: {
    title: string;
    links: {
      label: string;
      url: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  serviceArea?: string | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  phone?: T;
  logo?: T;
  siteUrl?: T;
  defaultOgImage?: T;
  social?:
    | T
    | {
        googleBusiness?: T;
        facebook?: T;
        nextdoor?: T;
        yelp?: T;
      };
  analytics?:
    | T
    | {
        ga4Id?: T;
        metaPixelId?: T;
        adwordsId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        text?: T;
        url?: T;
      };
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandDescription?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  serviceArea?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}