const cssVar = (name: string) => `var(${name})` as const;

export const theme = {
  font: {
    body: cssVar("--cc-font-body"),
    heading: cssVar("--cc-font-heading"),
    label: cssVar("--cc-font-label"),
    mono: cssVar("--cc-font-mono"),
  },
  color: {
    canvas: cssVar("--cc-canvas"),
    canvasSubtle: cssVar("--cc-canvas-subtle"),
    canvasMuted: cssVar("--cc-canvas-muted"),
    canvasOverlay80: cssVar("--cc-canvas-overlay-80"),
    canvasOverlay82: cssVar("--cc-canvas-overlay-82"),
    canvasOverlay92: cssVar("--cc-canvas-overlay-92"),
    text: {
      primary: cssVar("--cc-text-primary"),
      primaryAlt: cssVar("--cc-text-primary-alt"),
      secondary: cssVar("--cc-text-secondary"),
      tertiary: cssVar("--cc-text-tertiary"),
      muted: cssVar("--cc-text-muted"),
      faint: cssVar("--cc-text-faint"),
      inverse: cssVar("--cc-text-inverse"),
      onSelected: cssVar("--cc-text-on-selected"),
      linkMuted: cssVar("--cc-text-link-muted"),
      disabled: cssVar("--cc-text-disabled"),
    },
    brand: {
      primary: cssVar("--cc-brand-primary"),
      hover: cssVar("--cc-brand-hover"),
      strong: cssVar("--cc-brand-strong"),
      soft: cssVar("--cc-brand-soft"),
      softer: cssVar("--cc-brand-softer"),
      gradient: cssVar("--cc-brand-gradient"),
    },
    palette: {
      blue: cssVar("--cc-palette-blue"),
      green: cssVar("--cc-palette-green"),
      amber: cssVar("--cc-palette-amber"),
      purple: cssVar("--cc-palette-purple"),
      red: cssVar("--cc-palette-red"),
      pink: cssVar("--cc-palette-pink"),
      teal: cssVar("--cc-palette-teal"),
      orange: cssVar("--cc-palette-orange"),
      terracottaLight: cssVar("--cc-palette-terracotta-light"),
      terracottaLighter: cssVar("--cc-palette-terracotta-lighter"),
      successLight: cssVar("--cc-palette-success-light"),
      successMedium: cssVar("--cc-palette-success-medium"),
      slateSoft: cssVar("--cc-palette-slate-soft"),
      codeBg: cssVar("--cc-palette-code-bg"),
    },
  },
  surface: {
    base: cssVar("--cc-surface"),
    raised: cssVar("--cc-surface-raised"),
    muted: cssVar("--cc-surface-muted"),
    soft: cssVar("--cc-surface-soft"),
    selected: cssVar("--cc-surface-selected"),
    selectedSoft: cssVar("--cc-surface-selected-soft"),
    warning: cssVar("--cc-surface-warning"),
    warningSoft: cssVar("--cc-surface-warning-soft"),
    danger: cssVar("--cc-surface-danger"),
    dangerSoft: cssVar("--cc-surface-danger-soft"),
    success: cssVar("--cc-surface-success"),
    info: cssVar("--cc-surface-info"),
    purple: cssVar("--cc-surface-purple"),
    overlay: cssVar("--cc-surface-overlay"),
    card: cssVar("--cc-surface-muted"),
  },
  control: {
    bg: cssVar("--cc-control-bg"),
    bgHover: cssVar("--cc-control-bg-hover"),
    bgActive: cssVar("--cc-control-bg-active"),
    border: cssVar("--cc-control-border"),
    progressTrack: cssVar("--cc-progress-track"),
  },
  border: {
    subtle: cssVar("--cc-border-subtle"),
    default: cssVar("--cc-border-default"),
    medium: cssVar("--cc-border-medium"),
    strong: cssVar("--cc-border-strong"),
    stronger: cssVar("--cc-border-stronger"),
    brandSubtle: cssVar("--cc-border-brand-subtle"),
    brand: cssVar("--cc-border-brand"),
    brandStrong: cssVar("--cc-border-brand-strong"),
    success: cssVar("--cc-border-success"),
    warning: cssVar("--cc-border-warning"),
    danger: cssVar("--cc-border-danger"),
  },
  alpha: {
    brand02: cssVar("--cc-brand-alpha-02"),
    brand03: cssVar("--cc-brand-alpha-03"),
    brand04: cssVar("--cc-brand-alpha-04"),
    brand05: cssVar("--cc-brand-alpha-05"),
    brand06: cssVar("--cc-brand-alpha-06"),
    brand08: cssVar("--cc-brand-alpha-08"),
    brand10: cssVar("--cc-brand-alpha-10"),
    brand12: cssVar("--cc-brand-alpha-12"),
    brand15: cssVar("--cc-brand-alpha-15"),
    brand20: cssVar("--cc-brand-alpha-20"),
    brand25: cssVar("--cc-brand-alpha-25"),
    brand30: cssVar("--cc-brand-alpha-30"),
    brand35: cssVar("--cc-brand-alpha-35"),
    brand40: cssVar("--cc-brand-alpha-40"),
    brand45: cssVar("--cc-brand-alpha-45"),
    brand50: cssVar("--cc-brand-alpha-50"),
    line06: cssVar("--cc-line-alpha-06"),
    line08: cssVar("--cc-line-alpha-08"),
    line10: cssVar("--cc-line-alpha-10"),
    line12: cssVar("--cc-line-alpha-12"),
    line15: cssVar("--cc-line-alpha-15"),
    line20: cssVar("--cc-line-alpha-20"),
    line22: cssVar("--cc-line-alpha-22"),
    line25: cssVar("--cc-line-alpha-25"),
    line30: cssVar("--cc-line-alpha-30"),
    line34: cssVar("--cc-line-alpha-34"),
    line35: cssVar("--cc-line-alpha-35"),
    line40: cssVar("--cc-line-alpha-40"),
    line50: cssVar("--cc-line-alpha-50"),
    line70: cssVar("--cc-line-alpha-70"),
    neutral02: cssVar("--cc-neutral-alpha-02"),
    neutral03: cssVar("--cc-neutral-alpha-03"),
    neutral04: cssVar("--cc-neutral-alpha-04"),
    neutral05: cssVar("--cc-neutral-alpha-05"),
    neutral06: cssVar("--cc-neutral-alpha-06"),
    neutral08: cssVar("--cc-neutral-alpha-08"),
    neutral10: cssVar("--cc-neutral-alpha-10"),
    neutral12: cssVar("--cc-neutral-alpha-12"),
    neutral15: cssVar("--cc-neutral-alpha-15"),
    neutral20: cssVar("--cc-neutral-alpha-20"),
    neutral25: cssVar("--cc-neutral-alpha-25"),
    neutral35: cssVar("--cc-neutral-alpha-35"),
    neutral40: cssVar("--cc-neutral-alpha-40"),
  },
  status: {
    success: cssVar("--cc-status-success"),
    successHover: cssVar("--cc-status-success-hover"),
    successStrong: cssVar("--cc-status-success-strong"),
    successBright: cssVar("--cc-status-success-bright"),
    successBg: cssVar("--cc-status-success-bg"),
    successBgSoft: cssVar("--cc-status-success-bg-soft"),
    warning: cssVar("--cc-status-warning"),
    warningSoft: cssVar("--cc-status-warning-soft"),
    warningStrong: cssVar("--cc-status-warning-strong"),
    warningBright: cssVar("--cc-status-warning-bright"),
    warningBg: cssVar("--cc-status-warning-bg"),
    danger: cssVar("--cc-status-danger"),
    dangerHover: cssVar("--cc-status-danger-hover"),
    dangerBright: cssVar("--cc-status-danger-bright"),
    dangerAlt: cssVar("--cc-status-danger-alt"),
    dangerStrong: cssVar("--cc-status-danger-strong"),
    dangerBg: cssVar("--cc-status-danger-bg"),
    info: cssVar("--cc-status-info"),
    infoStrong: cssVar("--cc-status-info-strong"),
    infoBg: cssVar("--cc-status-info-bg"),
    purple: cssVar("--cc-status-purple"),
    purpleBright: cssVar("--cc-status-purple-bright"),
    purpleBg: cssVar("--cc-status-purple-bg"),
  },
  radius: {
    xs: cssVar("--cc-radius-xs"),
    sm: cssVar("--cc-radius-sm"),
    md: cssVar("--cc-radius-md"),
    lg: cssVar("--cc-radius-lg"),
    xl: cssVar("--cc-radius-xl"),
    round: cssVar("--cc-radius-round"),
  },
  shadow: {
    card: cssVar("--cc-shadow-card"),
    popover: cssVar("--cc-shadow-popover"),
    modal: cssVar("--cc-shadow-modal"),
    running: cssVar("--cc-shadow-running"),
    runningStrong: cssVar("--cc-shadow-running-strong"),
    focus: cssVar("--cc-focus-ring"),
    focusStrong: cssVar("--cc-focus-ring-strong"),
  },
  space: {
    1: cssVar("--cc-space-1"),
    2: cssVar("--cc-space-2"),
    3: cssVar("--cc-space-3"),
    4: cssVar("--cc-space-4"),
    5: cssVar("--cc-space-5"),
    6: cssVar("--cc-space-6"),
    8: cssVar("--cc-space-8"),
    10: cssVar("--cc-space-10"),
    12: cssVar("--cc-space-12"),
  },
  motion: {
    fast: cssVar("--cc-motion-fast"),
    standard: cssVar("--cc-motion-standard"),
    slow: cssVar("--cc-motion-slow"),
  },
} as const;

export type ThemeTokens = typeof theme;
